In [1]:
import numpy as np

In [2]:
valoraciones = np.array([[8,7,8,5], [2,6,8,1], [8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [3]:
valoraciones[0][1]

7

In [4]:
valoraciones[0,1]

7

In [18]:
valoraciones2 = np.array([[[8,7,8,5], [2,6,11,1]], [[7,5,2,12], [1,3,1,1]], [[9,10,1,6], [3,6,8,0]]])

In [19]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  6, 11,  1]],

       [[ 7,  5,  2, 12],
        [ 1,  3,  1,  1]],

       [[ 9, 10,  1,  6],
        [ 3,  6,  8,  0]]])

In [20]:
valoraciones2[0, 1, 2]

11

In [21]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7., 12.,  2.]],

       [[ 8.,  6.,  3., 13.],
        [ 2.,  4.,  2.,  2.]],

       [[10., 11.,  2.,  7.],
        [ 4.,  7.,  9.,  1.]]])

In [23]:
np.mean(valoraciones2)

5.125

In [27]:
np.mean(valoraciones2, axis=2)

array([[7.  , 5.  ],
       [6.5 , 1.5 ],
       [6.5 , 4.25]])

In [28]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
 np.median(df['Columna1'])

In [ ]:
np.random.rand(2,2)